function CwWerte0kPa = importdata_spreadsheet_new(workbookFile, sheetName, startRow, endRow)
%IMPORTFILE Import data from a spreadsheet
%  CWWERTE0KPA = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  CWWERTE0KPA = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  CWWERTE0KPA = IMPORTFILE(FILE, SHEET, STARTROW, ENDROW) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  STARTROW and ENDROW as a pair of scalars or vectors of matching size
%  for dis-contiguous row intervals.
%
%  Example:
%  CwWerte0kPa = importfile("C:\Users\Flo\Documents\GitHub\Stumpfkoerper-WS-18-19\40_Messung\Projektarbeit_WS_18_19\Daten\Walzenpaar 50\Aktuation\0kPa\Cw_Werte_0kPa.xlsx", "Tabelle1", 1, 1);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Jan-2019 14:10:03

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 1;
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + startRow(1) + ":L" + endRow(1);

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
CwWerte0kPa = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:length(startRow)
    opts.DataRange = "A" + startRow(idx) + ":L" + endRow(idx);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    CwWerte0kPa = [CwWerte0kPa; tb]; %#ok<AGROW>
end

%% Convert to output type
CwWerte0kPa = table2array(CwWerte0kPa);
end